accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('',views.myAccount),
    path('registerUser/',views.registerUser, name='registerUser'),
    path('registerVendor/',views.registerVendor, name='registerVendor'),

    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('myAccount/',views.myAccount,name='myAccount'),
    path('customerDashboard/',views.customerDashboard, name='customerDashboard'),
    path('vendorDashboard/',views.vendorDashboard, name='vendorDashboard'),

    path('activate/<uidb64>/<token>/',views.activate, name='activate'),

    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>/',views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/',views.reset_password, name='reset_password'),

   

]

food_vendor_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('accounts/',include('accounts.urls')),
    path('vendor/', include('vendor.urls')), 
    path('marketplace/', include('marketplace.urls')), 


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/urls.py
from django.urls import path, include
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('',views.marketplace,name='marketplace'),
    path('<slug:vendor_slug>/',views.vendor_detail,name='vendor_detail'),

    # Add to cart
    path('add_to_cart/<int:food_id>/',views.add_to_cart,name='add_to_cart'),
    # decrease cart
    path('decrease_cart/<int:food_id>/',views.decrease_cart,name='decrease_cart'),

]

marketplace/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem


class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    # user is foreignkey, thats why the unicode instead of __str__
    def __unicode__(self):
        return self.user

marketplace/views.py
from django.shortcuts import get_object_or_404, render
from .context_processors import get_cart_counter
from vendor.models import Vendor
from menu.models import Category,FoodItem
from django.db.models import Prefetch
from django.http import HttpResponse,JsonResponse
from .models import Cart


def marketplace(request):
    vendors = Vendor.objects.filter(is_approved=True, user__is_active=True)
    vendor_count = vendors.count()
    context = {
        'vendors':vendors,
        'vendor_count':vendor_count,
    }
    return render(request,'marketplace/listings.html',context)




def vendor_detail(request, vendor_slug):
    vendor = get_object_or_404(Vendor,vendor_slug=vendor_slug)
    
    # Accessing the food items from the category model using related name "fooditems" in the menu models
    # this way you can access the fooditems related to the category even when the category is not a foreignkey of Category table
    # And its called reverse lookup
    categories = Category.objects.filter(vendor=vendor).prefetch_related(
        Prefetch(
            'fooditems',
            queryset = FoodItem.objects.filter(is_available=True)
        )
    )
    if request.user.is_authenticated:
        cart_items = Cart.objects.filter(user=request.user)
    else:
        cart_items = None
    context = {
        'vendor':vendor,
        'categories':categories,
        'cart_items':cart_items,
    }
    return render(request,'marketplace/vendor_detail.html',context)




def add_to_cart(request, food_id):
    if request.user.is_authenticated:
        # check if its ajax request
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # Check if the food item exists
            try:
                fooditem = FoodItem.objects.get(id=food_id)
                # Check if the user has already added the food to the cart
                try:
                    check_cart = Cart.objects.get(user=request.user, fooditem=fooditem)
                    # increase cart quantity
                    check_cart.quantity += 1
                    check_cart.save()
                    return JsonResponse({'status':'Success','message':'Added one more of the same food item to the cart.','cart_counter':get_cart_counter(request), 'qty':check_cart.quantity})
                # if the user havn't already added the food to the cart the create the cart
                except:
                    check_cart = Cart.objects.create(user=request.user, fooditem=fooditem, quantity=1)
                    return JsonResponse({'status':'Success','message':'Added the food to the cart.','cart_counter':get_cart_counter(request), 'qty':check_cart.quantity})
            except:
                return JsonResponse({'status':'Failed','message':'This food does not exist.'})
        else:
            return JsonResponse({'status':'Failed','message':'Invalid request'})
    else: 
        return JsonResponse({'status':'login_required','message':'Please login to continue'})
    



def decrease_cart(request, food_id):
    if request.user.is_authenticated:
        # check if its ajax request
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # Check if the food item exists
            try:
                fooditem = FoodItem.objects.get(id=food_id)
                # Check if the user has already added the food to the cart
                try:
                    check_cart = Cart.objects.get(user=request.user, fooditem=fooditem)
                    if check_cart.quantity > 1 :
                        # decrease  cart quantity
                        check_cart.quantity -= 1
                        check_cart.save()
                    else:
                        check_cart.delete()
                        check_cart.quantity = 0
                    return JsonResponse({'status':'Success','cart_counter':get_cart_counter(request), 'qty':check_cart.quantity})
                # if the user havn't already added the food to the cart the create the cart
                except:
                    return JsonResponse({'status':'Failed','message':'You do not have this food in your cart.'})
            except:
                return JsonResponse({'status':'Failed','message':'This food does not exist.'})
        else:
            return JsonResponse({'status':'Failed','message':'Invalid request'})
    else: 
        return JsonResponse({'status':'login_required','message':'Please login to continue'})

templates/marketplace/listings.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 10px;margin-bottom: 0px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="row">
                        <aside class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                            
                        </aside>
                        <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                            <div class="listing-sorting-holder">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <h4>{{ vendor_count }} Restaurant's found</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="listing simple">
                                <ul>
                                    {% for vendor in vendors %}
                                    <li style="line-height: 15px;">
                                        <div class="img-holder">
                                            <figure>
                                                <a href="#">
                                                    {% if vendor.user_profile.profile_picture %}
                                                    <img src="{{ vendor.user_profile.profile_picture.url }}" class="img-list wp-post-image" alt="">
                                                    {% else %}
                                                    <img src="{% static 'images/default-profile.png' %}" class="img-list wp-post-image" alt="">
                                                    {% endif %}
                                                </a>
                                            </figure>
                                            {% if vendor.is_open %}
                                            <span class="restaurant-status open"><em class="bookmarkRibbon"></em>Open</span>
                                            {% else %}
                                            <span class="restaurant-status close"><em class="bookmarkRibbon"></em>Close</span>
                                            {% endif %}
                                        </div>
                                        <div class="text-holder">
                                            
                                            <div class="post-title">
                                                <h5>
                                                    <a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}">{{ vendor.vendor_name }}</a>
                                                </h5>
                                            </div>
                                            {% if vendor.user_profile.address %}
                                            <span><small class="text-muted">{{ vendor.user_profile.address }}</small></span>
                                            {% endif %}

                                            {% if source_location %}
                                            <br>
                                            <span><small><b>{{vendor.kms}}km</b> away from {{source_location}}</small></span>
                                            {% endif %}
                                        </div>
                                        <div class="list-option">

                                            <a href="{% url 'marketplace:vendor_detail' vendor.vendor_slug %}" class="viewmenu-btn text-color">View Menu</a>
                                        </div>
                                    </li>
                                    {% endfor %}
                                    
                                </ul>
                            </div>
                            
                        </div>
                        <div class="section-sidebar col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <div class="message-box" style="background-color: #fa9918;">
                                <strong>I'm not Listed!</strong><span>is your restaurant or
                                    business not
                                    listed on over site</span>
                                <a href="{% url 'accounts:registerVendor' %}" class="request-btn">Add Your business!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->

{% endblock %}

templates/marketplace/vendor_detail.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

<!-- Main Section Start -->
<div class="main-section">
    <div class="page-section restaurant-detail-image-section" style="background: url({% if vendor.user_profile.cover_photo %} {{ vendor.user_profile.cover_photo.url }} {% else %} {% static 'images/default-cover.png' %} {% endif %}) no-repeat scroll 0 0 / cover;">
        <!-- Container Start -->
        <div class="container">
            <!-- Row Start -->
            <div class="row">
                <!-- Column Start -->
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="company-info-detail">
                        <div class="company-info">
                            <div class="img-holder">
                                <figure>
                                    {% if vendor.user_profile.profile_picture %}
                                    <img src="{{ vendor.user_profile.profile_picture.url }}" alt="">
                                    {% else %}
                                    <img src="{% static 'images/default-profile.png' %}" alt="">
                                    {% endif %}
                                </figure>
                            </div>
                            <div class="text-holder">
                                <span class="restaurant-title">{{ vendor.vendor_name }} {% if not vendor.is_open %}[Closed]{% endif %}</span>
                                <div class="text">
                                    {% if vendor.user_profile.address %}
                                    <i class="icon-location"></i>
                                    <p>{{vendor.user_profile.address}}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% comment %}{% if opening_hours %}{% endcomment %}
                        <div class="delivery-timing reviews-sortby">
                            
                            <ul>
                                <li>
                                    <a href="#" class="reviews-sortby-active">
                                        <span>Today :</span>
                                        {% for i in current_opening_hours %}
                                        <span>{% if i.is_closed %}Closed{% else %}{{ i.from_hour }} - {{ i.to_hour }}{% endif %}</span>
                                        
                                        {% endfor %}
                                        <i class="icon-chevron-small-down"></i>
                                    </a>
                                    <ul class="delivery-dropdown">
                                        {% for hour in opening_hours %}
                                        <li><a href="#"><span class="opend-day">{{ hour }}</span> <span class="opend-time"><small>:</small>{% if hour.is_closed %}Closed{% else %}{{ hour.from_hour }} - {{ hour.to_hour }}{% endif %}</span></a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        {% comment %}{% endif %}{% endcomment %} 
                    </div>
                </div>
                <!-- Column End -->
            </div>
            <!-- Row End -->
        </div>
        <!-- Container End -->
    </div>

    <div class="page-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 sticky-sidebar">
                    
                    <div class="filter-wrapper">
                        <div class="categories-menu">
                            <h6><i class="icon-restaurant_menu"></i>Categories</h6>
                            <ul class="menu-list">
                                {% for category in categories %}
                                <li class="active"><a href="#" class="menu-category-link"> {{ category }} </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                    <div class="tabs-holder horizontal">
                        <ul class="stickynav-tabs nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Menu</a></li>
                            
                        </ul>
                        <div class="tab-content">
                            <div id="home" class="tab-pane in active">
                                <div class="menu-itam-holder">
                                    
                                    <div id="menu-item-list-6272" class="menu-itam-list">
                                        
                                        {% for category in categories %}
                                        <div class="element-title" id="menu-category-2">
                                            <h5 class="text-color">{{ category }}</h5>
                                            <span>{{ category.description }}</span>
                                        </div>
                                        <ul>
                                            {% for food in category.fooditems.all %}
                                            <li>
                                                <div class="image-holder"> <img src="{{ food.image.url }}" alt=""></div>
                                                <div class="text-holder">
                                                    <h6>{{ food.food_title }}</h6>
                                                    <span>{{ food.description }}</span>
                                                </div>
                                                <div class="price-holder">
                                                    <span class="price">${{ food.price }}</span>

                                                    <a href="#" class="decrease_cart" data-id="{{ food.id }}" data-url="{% url 'marketplace:decrease_cart' food.id %}" style="margin-right: 28px;"><i class="icon-minus text-color"></i></a>
                                                    <label id="qty-{{food.id}}">0</label>
                                                    <a href="#" class="add_to_cart" data-id="{{ food.id }}" data-url="{% url 'marketplace:add_to_cart' food.id %}"><i class="icon-plus4 text-color"></i></a>
                                                    
                                                </div>
                                            </li>
                                            {% endfor %}
                                            
                                        </ul>
                                        {% endfor %}
                                        
                                    </div>

                                    {% for item in cart_items %}

                                    <span id="qty-{{item.fooditem.id}}" class="item_qty d-none" data-qty="{{ item.quantity }}">{{ item.quantity }}</span>

                                    

                                    {% endfor %}
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->

{% endblock %}